import { AdminGuard } from '@/components/guards/AdminGuard';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AdminGuard fallbackUrl="/admin/dashboard">
      {children}
    </AdminGuard>
  );
}
